services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ZEKItorc0802!'
      MYSQL_DATABASE: cinetro
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mysql://root:ZEKItorc0802!@mysql:3306/cinetro'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis:
